use ehealth;
insert into speciality values(1, 'Cardiologist');
insert into speciality values(2, 'Cosmetic Surgeon');
insert into speciality values(3, 'Traumatologist Orthopedic Surgeon');
insert into speciality values(4, 'Dentist');
insert into speciality values(5, 'Dermatologist');
insert into speciality values(6, 'Endocrinologist Diabetologist');
insert into speciality values(7, 'Gastroenterologist');
insert into speciality values(8, 'Generalist');
insert into speciality values(9, 'Obstetrician Gynecologist');
insert into speciality values(10, 'Internist');
insert into speciality values(11, 'Nephrologist');
insert into speciality values(12, 'Neurologist');
insert into speciality values(13, 'Nutritionist');
insert into speciality values(14, 'Ophthalmologist');
insert into speciality values(15, 'Otorhinolaryngologist (ENT)');
insert into speciality values(16, 'Paediatrician');
insert into speciality values(17, 'Pneumologist');
insert into speciality values(18, 'Psychiatrist');
insert into speciality values(19, 'Psychotherapist');
insert into speciality values(20, 'Radiologist');
insert into speciality values(21, 'Rheumatologist');
insert into speciality values(22, 'Sex therapist');
insert into speciality values(23, 'Urologist');

/*country table*/
insert into country values ('1', 'Tunisia');
insert into country values (2, 'Algeria');
insert into country values (3, 'Morocco');
insert into country values (4, 'Egypt');
insert into country values (5, 'Turkey');
insert into country values (6, 'Saudi Arabia');
insert into country values (7, 'Senegal');

/*state table*/
insert into state values (1,'Tunis',1);
insert into state values (2,'Sfax',1);
insert into state values (3,'Sousse',1);
insert into state values (4,'Monastir',1);
insert into state values (5,'Ariana',1);
insert into state values (6,'Ben arous',1);
insert into state values (7,'Nabeul',1);
insert into state values (8,'Mahdia',1);
insert into state values (9,'Kairouan',	1);
insert into state values (10,'Bizerte',1);
insert into state values (11,'Medenine',1);
insert into state values (12,'Mannouba',1);
insert into state values (13,'Gabes',1);
insert into state values (14,'Beja',1);
insert into state values (15,'Gafsa',1);
insert into state values (16,'Jendouba',1);
insert into state values (17,'Le Kef',1);
insert into state values (18,'Sidi bouzid',1);
insert into state values (19,'Kasserine',1);
insert into state values (20,'Zaghouan',1);
insert into state values (21,'Siliana',1);
insert into state values (22,'Kebili',1);
insert into state values (23,'Tataouine',	1);
insert into state values (24,'Tozeur',1);
insert into state values (25,'Adana',5);
insert into state values (26,'Adıyaman'	,5);
insert into state values (27,'Afyon Karahisar',	5);

/*city table*/
insert into city values (1,'	Abou El Kacem Chebbi',	1);
insert into city values (2,'	Aîn Zaghouan',	1);
insert into city values (3,	'Bab Alioua',	1);
insert into city values (4,	'Bab Bhar'	,1);
insert into city values (5,	'Bab El Akoues'	,1);
insert into city values (6	,'Bab El Alouj'	,1);
insert into city values (7,'	Bab El Assel'	,1);
insert into city values (8,'Bab El Falla'	,1);
insert into city values (9,	'Bab El Jazira'	,1);
insert into city values (10,	'Bab El Khadra',	1);
insert into city values (11,	'Bab Saadoun'	,1);
insert into city values (12,	'Bab Saadoun Gare',	1);
insert into city values (13,	'Bab Sidi Abdessalem'	,1);
insert into city values (14,	'Bab Souika',	1);
insert into city values (15,	'Bellevue'	,1);
insert into city values (16,	'Bir El Hlou'	,1);
insert into city values (17,	'Birine',	1);
insert into city values (18,	'Borj Ali Errais'	,1);
insert into city values (19	,'Borj Chakir'	,1);
insert into city values (20,	'Borj Zouara'	,1);
insert into city values (21,	'Bortal Hayder'	,1);
insert into city values (22,	'Bouchoucha'	,1);
insert into city values (23	,'Carthage'	,1);
insert into city values (24,	'Centre Urbain Nord',	1);
insert into city values (25,	'Cite 14 Janvier',	1);
insert into city values (26,	'Agareb'	,2);
insert into city values (27,	'Aguegcha'	,2);
insert into city values (28,	'Ain Charfi'	,2);
insert into city values (29,	'Ain El Fellat',	2);
insert into city values (30,	'Ain El Ghezal'	,2);
insert into city values (31,	'Ain El Mayel',	2);
insert into city values (32,	'Ain Tourkia',	2);
insert into city values (33,	'Ain Turki'	,2);
insert into city values (34,	'Ajenga'	,2);
insert into city values (35,	'Bab El Jebli'	,2);
insert into city values (36,	'Bechka',	2);
insert into city values (37,	'Beliana	',2);
insert into city values (38,	'Ben Sahloun'	,2);
insert into city values (39,	'Bir Ali Ben Khelifa',	2);
insert into city values (40,	'Bir Ben Ayed'	,2);
insert into city values (41,	'Bir El Mellouli',	2);
insert into city values (42,'Bir Tebak'	,2);
insert into city values (43,	'Blitech'	,2);
insert into city values (44,	'Bou Jarbou'	,2);
insert into city values (45,	'Bou Said'	,2);
insert into city values (46,	'Aeroport Tunis Carthage',	5);
insert into city values (47,	'Ariana Essoughra',	5);
insert into city values (48,	'Ariana Ville',	5);
insert into city values (49,	'Bejaoua 2'	,5);
insert into city values (50,	'Borj El Baccouche'	,5);
insert into city values (51,	'Borj Louzir',	5);
insert into city values (52,	'Borj Touil',	5);
insert into city values (53,	'Borj Youssef'	,5);
insert into city values (54,	'Bou Hnech',	5);
insert into city values (55,	'Cebalet Ben Ammar'	,5);
insert into city values (56,	'Charguia 1'	,5);
insert into city values (57,	'Charguia 2'	,5);
insert into city values (58,	'Chorfech'	,5);
insert into city values (59,	'Chorfech 2',	5);
insert into city values (60,	'Chorfech 24',	5);
insert into city values (61,	'Chorfech 8'	,5);
insert into city values (62,	'Chotrana 1'	,5);
insert into city values (63,	'Chotrana 2',	5);
insert into city values (64,	'Chotrana 3',	5);
insert into city values (65,	'Cite 18 Janvier',	5);